# Generated by Django 3.1.5 on 2021-01-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(max_length=255)),
                ('data_hora', models.CharField(max_length=255)),
                ('memoria', models.IntegerField()),
                ('cpu', models.IntegerField()),
            ],
        ),
    ]
