# Generated by Django 3.1.5 on 2021-01-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='cpu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='memoria',
            field=models.FloatField(),
        ),
    ]
