# Generated by Django 3.1.5 on 2021-01-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20210107_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipamento',
            new_name='Registro',
        ),
    ]
