# Generated by Django 3.1.5 on 2021-01-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20210107_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='clock_processador',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='memoria_total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
