# Generated by Django 3.1.5 on 2021-01-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_auto_20210127_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='clock_processador',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
