# Generated by Django 3.1.5 on 2021-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_auto_20210127_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='cores',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
