# Generated by Django 3.1.5 on 2021-01-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_registro_cores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='cores',
            new_name='quantidade_cores',
        ),
    ]
